### ISSUE TITLE
Status on Repo being populated?

### ISSUE THREAD

**Issue by pallen1405** [jasoncdavis/CiscoLiveNOC23US#1]
@jasoncdavis we love your work on the NOC each year a CLUS! do you have a timeframe that the tools/code will be available here to see in detail how you built and queried everything?

**Comment by jasoncdavis** [comment]
Hey @pallen1405 - I'm working this week and next to populate much of the repo.  Apologies for the template placeholder, but I needed something to point people to while at the event.

I recently opened SSH2Influx.  You might check that out in the other repo at https://github.com/jasoncdavis/SSH2Influx

Please standby for updates coming to this repo in the next few weeks.
